In [ ]:
#import libraries
import pandas as pd

In [ ]:
# upload files
amazon = pd.read_csv("/content/amazon_cells_labelled.txt", sep="\t", header=None)
imdb = pd.read_csv("/content/imdb_labelled.txt", sep="\t", header=None)
yelp = pd.read_csv("/content/yelp_labelled.txt", sep="\t", header=None)

In [ ]:
# inspect data
amazon.head()
imdb.head()
yelp.head()

                                                   0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [ ]:
# name data columns

amazon.columns = ["review", "sentiment"]
imdb.columns = ["review", "sentiment"]
yelp.columns = ["review", "sentiment"]
amazon.head()
imdb.head()
yelp.head()

                                              review  sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [ ]:
# Combine all three data sets

df = pd.concat([amazon, imdb, yelp], ignore_index=True)

In [ ]:
# check data shape

df.shape

(2748, 2)

In [ ]:
# check missing values

df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [ ]:
# check how many negative or positive values are in the dataset

df["sentiment"].value_counts()

sentiment
1    1386
0    1362
Name: count, dtype: int64

In [ ]:
# import train test split from sklearn

from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df["review"],
    df["sentiment"],
    test_size=0.2,
    random_state=42,
    stratify=df["sentiment"]
)

In [ ]:
# convert text into numbers

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [ ]:
# train the logistic regression model

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train_tfidf, y_train)

LogisticRegression()

In [ ]:
# check model accuracy

from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test_tfidf)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.82

In [ ]:
# check precision, recall F1 score

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.85      0.82       273
           1       0.84      0.79      0.82       277

    accuracy                           0.82       550
   macro avg       0.82      0.82      0.82       550
weighted avg       0.82      0.82      0.82       550

In [ ]:
# save model

import joblib

joblib.dump(model, "sentiment_model.pkl")
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

['tfidf_vectorizer.pkl']

In [ ]:
# real time model testing - a positive review

text = ["I absolutely loved this product. It was amazing!"]

text_tfidf = vectorizer.transform(text)
prediction = model.predict(text_tfidf)
if prediction[0] == 1:
    print("Positive 😊")
else:
    print("Negative 😞")

Positive 😊

In [25]:
# real time model testing - a negative review

text = ["This product is terrible. I am very disappointed."]

text_tfidf = vectorizer.transform(text)
prediction = model.predict(text_tfidf)
if prediction[0] == 1:
    print("Positive 😊")
else:
    print("Negative 😞")

Negative 😞

In [26]:
# download modified dataset

df.to_csv("df.csv", index=False)